# Generated by Django 4.2.4 on 2023-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('attendees', models.TextField()),
                ('description', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_online_meeting', models.BooleanField(default=False)),
                ('online_meeting_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('web_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
