# Generated by Django 4.2.4 on 2023-08-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_orgranizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orgranizer',
            new_name='organizer',
        ),
    ]
