# Generated by Django 4.2.4 on 2023-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_orgranizer_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='web_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
